[package]
name = "clafrica-wish"
version = "0.2.0"
edition = "2021"
description = "Wish interface for the clafrica."
repository = "https://github.com/pythonbrad/clafrica"
license = "MIT"
readme = "README.md"
authors = ["Fomegne Brady <fomegnemeudje@outlook.com>"]
keywords = ["african", "ime", "typing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clafrica = "0.2.1"
rstk = "0.1.0"
serde = { version = "1.0.163", features = ["serde_derive"] }
toml = "0.7.3"
