[build]
pre-build = [
    # additional commands to run prior to building the package
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install -y pkg-config libxdo-dev xorg-dev"
]                 
env = { passthrough = ["PKG_CONFIG_ALLOW_CROSS=1"] }
