name: Rust

on:
  workflow_dispatch:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          # To only cache runs from `master`
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - if: matrix.os == 'ubuntu-latest'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxtst-dev libevdev-dev libxdo-dev
          version: 1.0

      - name: Add components
        run: rustup component add clippy rustfmt

      - name: Rustfmt
        run: |
          cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      
      - name: Build
        run: cargo build --all-features --verbose

      - name: Test
        run: cargo test --all-features --verbose
